### ISSUE TITLE
Don't need to query via ODBC

### ISSUE THREAD

**Issue by iamwithnail** [GLC-gn/get_vis_and_dels#1]
With the Delegeates, even though they're in a different database, you don't need to use pypy/raw SQL to access - you can just do: 

```
from events.models import Delegate
delegates = Delegate.objects.filter(itemcode__in=['DEL'], confcode='GE6RESIL').only(['Postcode', BusinessUnit']) 

```

The issue with the conference codes not matching has been resolved via Solve360 - the stuff coming in from ERC was wrong.

**Comment by GLC-gn** [comment]
Ohhh, I see, cool, gracias!!!

**Comment by GLC-gn** [comment]
Done!
